### ISSUE TITLE
注册中心有问题？

### ISSUE THREAD

**Issue by ivanljc2017** [sofastack/sofa-registry#101]
### Your question
朋友提供的sofa registry，直接启动的那种。
启动后有问题，使用RPC程序客户端调服务端时出现错误。
日志见后面。
请大虾帮忙看看。
[logs.zip](https://github.com/sofastack/sofa-registry/files/4453932/logs.zip)

**Comment by ivanljc2017** [comment]
> Hi @ivanljc2017, we detect non-English characters in the issue. This comment is an auto translation by [@sofastack-robot](https://github.com/apps/sofastack-bot) to help other users to understand this issue.
> 
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> ### Your question The sofa registry provided by a friend, the one that starts directly. There is a problem after startup. An error occurs when using the RPC program client to call the server. See the log below. Please prawn help. [logs.zip] (https://github.com/sofastack/sofa-registry/files/4453932/logs.zip)

Thanks

**Comment by ivanljc2017** [comment]
add the question describe:
I excuted BalanceMngApplication and StockMngApplication.And  logined the  http://localhost:8080.The error occurs.
See the Stock-mng/logs  below.

**Comment by ivanljc2017** [comment]
stock-mng/logs 
[stock-mng-logs.zip](https://github.com/sofastack/sofa-registry/files/4454646/stock-mng-logs.zip)

**Comment by khotyn** [comment]
直接启动的 SOFARegistry？具体是什么版本的？最好有版本的信息。

**Comment by ivanljc2017** [comment]
我打包一个上来好了，你帮忙看看有什么问题。
文件太大，上传不了，截个图吧，5.4.2版本的。
![版本](https://user-images.githubusercontent.com/26160057/79100944-2789cf80-7d9a-11ea-80fc-15da0c63482e.png)

**Comment by ivanljc2017** [comment]
@khotyn ,我说的直接启动是在bin目录下执行startup.bat执行。

**Comment by khotyn** [comment]
@ivanljc2017 好的。

**Comment by ivanljc2017** [comment]
@khotyn ,启动的时候logs/common-error.log报错如下：
2020-04-08 14:31:10,600 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-11] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9610
2020-04-08 14:31:10,639 ERROR [RpcHeartbeatTrigger$2#142] [bolt-netty-client-worker-1-thread-4] Send heartbeat failed! Id=30477, to remoteAddr=192.168.43.36:9620
2020-04-08 14:31:11,594 ERROR [RpcRequestProcessor$1#194] [Rpc-netty-server-worker-6-thread-1] Rpc response send failed! id=30470. The address is 192.168.43.36:58637
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
2020-04-08 14:31:10,609 ERROR [RpcHeartbeatTrigger$2#142] [bolt-netty-client-worker-1-thread-1] Send heartbeat failed! Id=30475, to remoteAddr=192.168.43.36:9614
2020-04-08 14:31:11,599 ERROR [RpcRequestProcessor#252] [Bolt-default-executor-4-thread-5] SYNC process rpc request failed in RpcRequestProcessor, id=30469
java.lang.RuntimeException: Node renew error!
	at com.alipay.sofa.registry.server.meta.remoting.handler.RenewNodesRequestHandler.reply(RenewNodesRequestHandler.java:48)
	at com.alipay.sofa.registry.server.meta.remoting.handler.RenewNodesRequestHandler.reply(RenewNodesRequestHandler.java:33)
	at com.alipay.sofa.registry.remoting.bolt.SyncUserProcessorAdapter.handleRequest(SyncUserProcessorAdapter.java:54)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:239)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:145)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Proxy invoke interface com.alipay.sofa.registry.server.meta.repository.RepositoryService method replace got error!
	at com.alipay.sofa.registry.jraft.processor.ProxyHandler.invoke(ProxyHandler.java:73)
	at com.sun.proxy.$Proxy51.replace(Unknown Source)
	at com.alipay.sofa.registry.server.meta.store.DataStoreService.renew(DataStoreService.java:182)
	at com.alipay.sofa.registry.server.meta.store.DataStoreService.renew(DataStoreService.java:60)
	at com.alipay.sofa.registry.server.meta.registry.MetaServerRegistry.renew(MetaServerRegistry.java:78)
	at com.alipay.sofa.registry.server.meta.remoting.handler.RenewNodesRequestHandler.reply(RenewNodesRequestHandler.java:45)
	... 8 common frames omitted
Caused by: java.lang.RuntimeException: Send process request error!Connection closed! the address is 192.168.43.36:9614
	at com.alipay.sofa.registry.jraft.bootstrap.RaftClient.sendRequest(RaftClient.java:213)
	at com.alipay.sofa.registry.jraft.processor.ProxyHandler.invoke(ProxyHandler.java:69)
	... 13 common frames omitted
Caused by: com.alipay.remoting.exception.ConnectionClosedException: Connection closed! the address is 192.168.43.36:9614
	at com.alipay.remoting.rpc.RpcResponseResolver.preProcess(RpcResponseResolver.java:91)
	at com.alipay.remoting.rpc.RpcResponseResolver.resolveResponseObject(RpcResponseResolver.java:54)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:186)
	at com.alipay.remoting.rpc.RpcClientRemoting.invokeSync(RpcClientRemoting.java:64)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:143)
	at com.alipay.remoting.rpc.RpcClient.invokeSync(RpcClient.java:291)
	at com.alipay.sofa.registry.jraft.bootstrap.RaftClient.sendRequest(RaftClient.java:194)
	... 14 common frames omitted
2020-04-08 14:31:11,600 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-6] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9620
2020-04-08 14:31:11,600 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-6] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9614
2020-04-08 14:31:10,630 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-17] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9620
2020-04-08 14:31:10,630 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-4] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9620
2020-04-08 14:31:10,630 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-13] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9610
2020-04-08 14:31:10,618 ERROR [RpcHeartbeatTrigger$2#142] [bolt-netty-client-worker-1-thread-2] Send heartbeat failed! Id=30476, to remoteAddr=192.168.43.36:9620
2020-04-08 14:31:11,608 ERROR [RpcHeartbeatTrigger$1#112] [Bolt-default-executor-4-thread-1] Heartbeat exception caught! Error code=CONNECTION_CLOSED, The address is 192.168.43.36:9620
2020-04-08 14:31:11,624 ERROR [RpcRequestProcessor$1#194] [Rpc-netty-server-worker-6-thread-2] Rpc response send failed! id=30469. The address is 192.168.43.36:58651
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

**Comment by khotyn** [comment]
@ivanljc2017 问下你参考的是啥文档跑的 Demo？

**Comment by ivanljc2017** [comment]
参考的是这个：
https://www.sofastack.tech/guides/sofastack-quick-start/
