### ISSUE TITLE
求助registry 启动报错

### ISSUE THREAD

**Issue by tylorswift** [sofastack/sofa-registry#104]
### Your question

registry-integeration 集成部署启动后 common-error.log 报错 ，单三种health check 均显示正常

### 报错信息
[2020-04-14 18:15:50,507][ERROR][DataNodeChangePushTaskSessionDispatcher-7][SessionNodeServiceImpl] - Push sessionNode list error! No session node connected!
[2020-04-14 18:15:50,507][ERROR][DataNodeChangePushTaskDataDispatcher-1][DataNodeServiceImpl] - Push dataNode list error! No data node registered!
[2020-04-14 18:15:50,511][ERROR][DataNodeChangePushTaskSessionDispatcher-7][DataNodeSingleTaskProcessor] - [Task] Data node SingleTask Process error!
java.lang.RuntimeException: Push sessionNode list error! No session node connected!
	at com.alipay.sofa.registry.server.meta.node.impl.SessionNodeServiceImpl.pushDataNodes(SessionNodeServiceImpl.java:131)
	
[2020-04-14 18:15:51,795][ERROR][main][RegistryApplication] - localhost:9622 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)

**Comment by khotyn** [comment]
Checking this problem on the way.

**Comment by khotyn** [comment]
能否把日志目录下完整的日志给贴上来。

**Comment by khotyn** [comment]
可以打个包放上来，另外启动过程中前几次 HealthCheck 是有可能失败的，因为在等待 Data 节点 Ready，过了几次应该就成功了才对。

**Comment by tylorswift** [comment]
[logs.zip](https://github.com/sofastack/sofa-registry/files/4496444/logs.zip) 启动过很多次，分别尝试过两台电脑，偶尔有一次能成功 但极少次，session节点应该是9603端口吧 也是启动的

**Comment by khotyn** [comment]
看了下错误的日志，应该是不影响后面的使用，启动过程中有些节点没有 Ready，导致健康检查有问题，但是最终健康检查通过，启动成功了。

**Comment by khotyn** [comment]
可以通过访问以下的地址看下服务是否注册上来了：

```
http://localhost:9603/digest/PUB/data/query?dataInfoId=com.example.demo.SampleService:1.0@DEFAULT%23@%23DEFAULT_INSTANCE_ID%23@%23SOFA
```

":1.0" 之前的为接口名，后面的在 SOFA RPC 的情况下是固定字符串。

**Comment by tylorswift** [comment]
[spring.log](https://github.com/sofastack/sofa-registry/files/4496613/spring.log)
官网demo  BalanceMng 和 StockMng(web) 调用错误

**Comment by khotyn** [comment]
@tylorswift 我跑下 Demo 看看。

**Comment by khotyn** [comment]
@tylorswift 确认教程应该没有什么问题，你的 BalanceMngImpl 这个类上打上了下面的注解了吗？

```java
@SofaService(interfaceType = BalanceMngFacade.class, uniqueId = "${service.unique.id}", bindings = { @SofaServiceBinding(bindingType = "bolt") })
class BalanceMngImpl implements BalanceMngFacade {
}
```

**Comment by khotyn** [comment]
另外，服务注册的日志里面发现了比较多这样的：

```
RPC-00203: UnPublish RPC service：[io.sofastack.spring.balance.manage.facade.BalanceMngFacade:1.0:dongtailai@DEFAULT]	num: [1] 
```

最好是 BalanceMngApplication 启动之后，从服务注册中心上 Query 看下对应的服务是否注册上去了。

**Comment by tylorswift** [comment]
同一主机 BalanceMngFacade （找不到服务），StockMngFacade（找到服务）(web项目这个是本地调用吧) 
![error](https://user-images.githubusercontent.com/16263536/79677765-30a9ef00-8227-11ea-8057-6ca31e22b540.png)

**Comment by tylorswift** [comment]
极少数次能调用成功 ，且会报超时错误：Caused by: com.alipay.remoting.rpc.exception.InvokeTimeoutException: Rpc invocation timeout[responseCommand TIMEOUT]! the address is 192.168.43.251:22200，然后就是又是找不到Balance服务。是客户端故障剔除么  ？

**Comment by tylorswift** [comment]
超时时间能改大点么？
![error](https://user-images.githubusercontent.com/16263536/79678364-5934e780-822d-11ea-8f97-7b8d105eb3b0.png)

**Comment by khotyn** [comment]
我昨天看了你的日志，似乎 BalanceMngFacade 这个服务一会儿注册一会儿又取消了注册。BalanceMngFacade 所在的应用你是一直启动着的吧？

**Comment by khotyn** [comment]
看 Pub 也是有数据的。

**Comment by tylorswift** [comment]
一直启动的  ,其他人也遇到同样问题 应该是generally

**Comment by khotyn** [comment]
@tylorswift 能否把你的代码做一遍 mvn clean，然后打个包上传上来，我直接用你的试一下，虽然都是用的官方 Demo，但是可能改动的地方不一样之类的，我看下能否在我本地重现。

**Comment by tylorswift** [comment]
[kc-sofastack-demo-master.zip](https://github.com/sofastack/sofa-registry/files/4499081/kc-sofastack-demo-master.zip)   registry-integeration 是最新版的

**Comment by khotyn** [comment]
@tylorswift 好吧，我试下 Windows 下的，一直用的 Mac

**Comment by tylorswift** [comment]
@khotyn 方便的话可以 可以远程看一下  免得准备环境

**Comment by tylorswift** [comment]
@khotyn 你好 有结果了么？

**Comment by khotyn** [comment]
@tylorswift 周末我再看下哈
