### ISSUE TITLE
安装registry-integration.tgz 5.4.2 启动报错

### ISSUE THREAD

**Issue by xingguangdage** [sofastack/sofa-registry#107]
java与版本：
# java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
# mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /data/apache-maven-3.3.9
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /root/jdk1.8.0_171/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.1.2.el7.x86_64", arch: "amd64", family: "unix"
操作系统版本：
# uname -a
Linux k8s-master01 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
修改配置文件，178.56.23.11为本机ip
# cat application.properties
nodes.metaNode=DefaultDataCenter:178.56.23.11
nodes.localDataCenter=DefaultDataCenter
nodes.localRegion=DEFAULT_ZONE

安装registry-integration.tgz 5.4.2

启动报错；
[2020-04-26 15:15:52,296][ERROR][main][RegistryApplication] - 178.56.23.11:9615 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-26 15:15:52,296][ERROR][main][RegistryApplication] - 178.56.23.11:9615 health check failed.
查看端口无占用情况
# netstat -anultp|grep -w 96[0-9][0-9]
tcp6       0      0 :::9610                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9611                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9612                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9614                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9615                 :::*                    LISTEN      7634/java           
tcp6       0      0 178.56.23.11:55362     178.56.23.11:9614      ESTABLISHED 7634/java           
tcp6       0      0 178.56.23.11:9614      178.56.23.11:55362     ESTABLISHED 7634/java           
tcp6       0      0 178.56.23.11:38166     178.56.23.11:9615      ESTABLISHED 7634/java           
tcp6       0      0 178.56.23.11:9615      178.56.23.11:38166     ESTABLISHED 7634/java           
# ps -ef|grep 7634
root      7634     1  8 15:14 pts/2    00:00:20 java -Dregistry.integration.home=/data/registry-integration -Dspring.config.location=/data/registry-integration/conf/application.properties -Duser.home=/data/registry-integration -server -Xms512m -Xmx512m -Xmn256m -Xss256k -XX:+DisableExplicitGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/data/registry-integration/logs/registry-integration-gc.log -verbose:gc -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/registry-integration/logs -XX:ErrorFile=/data/registry-integration/logs/registry-integration-hs_err_pid%p.log -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -jar /data/registry-integration/registry-integration.jar --logging.config=/data/registry-integration/conf/logback-spring.xml
root      8371  7099  0 15:18 pts/2    00:00:00 grep --color=auto 7634

**Comment by Synex-wh** [comment]
这个目前看是健康检查失败了，启动是否还有其他报错，可以把启动日志发出来完整看看，此外可以手工执行一下curl -i http://localhost:9615/health/check看看结果，这个是和上述健康检查效果一样的。

**Comment by xingguangdage** [comment]
# curl -i http://localhost:9615/health/check
HTTP/1.1 500 Internal Server Error
Date: Mon, 27 Apr 2020 07:59:10 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.4.19.v20190610)

{"success":false,"message":"MetaServerBoot sessionRegisterServer:true, dataRegisterServerStart:true, otherMetaRegisterServerStart:true, httpServerStart:true, raftServerStart:true, raftClientStart:true, raftManagerStart:true, raftStatus:false"}

**Comment by xingguangdage** [comment]
registry-raft.log
[2020-04-27 00:08:44,716][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:44,716][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.
[2020-04-27 00:08:46,001][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:46,001][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.
[2020-04-27 00:08:47,347][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:47,347][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.
[2020-04-27 00:08:48,540][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:48,541][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.
[2020-04-27 00:08:49,824][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:49,824][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.
[2020-04-27 00:08:51,728][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:51,728][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.
[2020-04-27 00:08:53,208][INFO][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> term 0 start preVote.
[2020-04-27 00:08:53,208][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.

**Comment by xingguangdage** [comment]
common-error.log与registry-integration-std.out输出一样，就是我开始那段启动报错日志

**Comment by xingguangdage** [comment]
registry-integration-std.out启动输出
Command: java  -Dregistry.integration.home=/data/registry-integration -Dspring.config.location=/data/registry-integration/conf/application.properties -Duser.home=/data/registry-integration -server -Xms512m -Xmx512m -Xmn256m -Xss256k -XX:+DisableExplicitGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/data/registry-integration/logs/registry-integration-gc.log -verbose:gc -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/registry-integration/logs -XX:ErrorFile=/data/registry-integration/logs/registry-integration-hs_err_pid%p.log -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -jar /data/registry-integration/registry-integration.jar  --logging.config=/data/registry-integration/conf/logback-spring.xml
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Logback ]
[2020-04-27 16:17:41,753][INFO][main][MetaServerBootstrap] - the configuration items are as follows: com.alipay.sofa.registry.server.meta.bootstrap.MetaServerConfigBean@3e694b3f[
  sessionServerPort=9610
  dataServerPort=9611
  metaServerPort=9612
  httpServerPort=9615
  schedulerHeartbeatTimeout=3
  schedulerHeartbeatFirstDelay=3
  schedulerHeartbeatExpBackOffBound=10
  schedulerGetDataChangeTimeout=5
  schedulerGetDataChangeFirstDelay=5
  schedulerGetDataChangeExpBackOffBound=5
  schedulerConnectMetaServerTimeout=3
  schedulerConnectMetaServerFirstDelay=3
  schedulerConnectMetaServerExpBackOffBound=10
  schedulerCheckNodeListChangePushTimeout=3
  schedulerCheckNodeListChangePushFirstDelay=1
  schedulerCheckNodeListChangePushExpBackOffBound=10
  dataNodeExchangeTimeout=3000
  sessionNodeExchangeTimeout=3000
  metaNodeExchangeTimeout=3000
  dataCenterChangeNotifyTaskRetryTimes=3
  dataNodeChangePushTaskRetryTimes=1
  getDataCenterChangeListTaskRetryTimes=3
  receiveStatusConfirmNotifyTaskRetryTimes=3
  sessionNodeChangePushTaskRetryTimes=3
  enableMetrics=true
  decisionMode=<null>
  raftDataPath=/data/registry-integration/raftData
  rockDBCacheSize=64
  heartbeatCheckExecutorMinSize=3
  heartbeatCheckExecutorMaxSize=10
  heartbeatCheckExecutorQueueSize=1024
  checkDataChangeExecutorMinSize=3
  checkDataChangeExecutorMaxSize=10
  checkDataChangeExecutorQueueSize=1024
  getOtherDataCenterChangeExecutorMinSize=3
  getOtherDataCenterChangeExecutorMaxSize=10
  getOtherDataCenterChangeExecutorQueueSize=1024
  connectMetaServerExecutorMinSize=3
  connectMetaServerExecutorMaxSize=10
  connectMetaServerExecutorQueueSize=1024
  checkNodeListChangePushExecutorMinSize=3
  checkNodeListChangePushExecutorMaxSize=10
  checkNodeListChangePushExecutorQueueSize=1024
  raftClientRefreshExecutorMinSize=3
  raftClientRefreshExecutorMaxSize=10
  raftClientRefreshExecutorQueueSize=1024
  metaSchedulerPoolSize=6
]
[2020-04-27 16:17:41,805][INFO][main][MetaServerBootstrap] - Open session node register server port 9610 success!
[2020-04-27 16:17:41,806][INFO][main][MetaServerBootstrap] - Open data node register server port 9611 success!
[2020-04-27 16:17:41,807][INFO][main][MetaServerBootstrap] - Open meta server port 9612 success!
[2020-04-27 16:17:42,482][INFO][main][MetaServerBootstrap] - Open http server port 9615 success!
[2020-04-27 16:17:42,728][INFO][main][MetaServerBootstrap] - Raft server port 9614 start success!group RegistryGroup
[2020-04-27 16:17:42,728][INFO][main][MetaServerBootstrap] - Raft client connect success!
[2020-04-27 16:17:42,730][INFO][main][MetaServerBootstrap] - Raft start CliService success!
[2020-04-27 16:17:42,731][INFO][main][MetaServerInitializerConfiguration] - Started MetaServer
[2020-04-27 16:17:43,204][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-27 16:17:43,205][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.
[2020-04-27 16:17:44,219][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-27 16:17:44,220][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.
[2020-04-27 16:17:45,223][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-27 16:17:45,223][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.

**Comment by straybirdzls** [comment]
> [2020-04-27 00:08:53,208][WARN][JRaft-ElectionTimer][NodeImpl] - Node <RegistryGroup_DefaultDataCenter/172.17.0.1:9614> can't do preVote as it is not in conf <ConfigurationEntry [id=LogId [index=0, term=0], conf=178.56.23.11:9614, oldConf=]>.

@xingguangdage 能否确认下 172.17.0.1 以及 178.56.23.11 是一个机器不同的网卡地址吗？

**Comment by xingguangdage** [comment]
没有，178.56.23.11这个是我改了的

**Comment by straybirdzls** [comment]
@xingguangdage 改了是什么意思？

**Comment by xingguangdage** [comment]
# ifconfig -a
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:3b:22:14:f2  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.27.255.41  netmask 255.255.255.0  broadcast 172.27.255.255
        inet6 fe80::216:3eff:fe03:3349  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:03:33:49  txqueuelen 1000  (Ethernet)
        RX packets 966213866  bytes 130134328658 (121.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1058064796  bytes 99619440673 (92.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 598360817  bytes 74594399340 (69.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 598360817  bytes 74594399340 (69.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by xingguangdage** [comment]
我粘贴日志把172.27.255.41改成了178.56.23.11

**Comment by straybirdzls** [comment]
@xingguangdage 看起来是因为在 docker 下跑带来的问题，我这边看下，估计需要添加什么参数

**Comment by straybirdzls** [comment]
@xingguangdage 你目前希望绑定哪张网卡？看 `nodes.metaNode=DefaultDataCenter:178.56.23.11
` (对应到 172.27.255.41)你是想绑定 eth0 吧？那修改下 start.sh ，加个启动参数 `-Dnetwork_interface_binding=eth0`

**Comment by xingguangdage** [comment]
这个参数怎么加？是这么加
是在startup.sh里这么加
java ${JAVA_OPTS} -jar ${APP_JAR} ${SPRINGBOOT_OPTS} -Dnetwork_interface_binding=eth0 >> "$STD_OUT" 2>&1 &
还是在上面配置上，两种方法我都试了，还是报错
Dnetwork_interface_binding

**Comment by straybirdzls** [comment]
@xingguangdage 这么加：

![image](https://user-images.githubusercontent.com/7148759/80354805-d1dd1900-88a9-11ea-99fe-070569d2494f.png)

内容为： `+JAVA_OPTS="$JAVA_OPTS -Dnetwork_interface_binding=eth0 "`

**Comment by xingguangdage** [comment]
报错
# sh startup.sh
startup.sh: line 43: +JAVA_OPTS= -Dregistry.integration.home=/data/registry-integration -Dspring.config.location=/data/registry-integration/conf/application.properties -Duser.home=/data/registry-integration -server -Xms512m -Xmx512m -Xmn256m -Xss256k -XX:+DisableExplicitGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/data/registry-integration/logs/registry-integration-gc.log -verbose:gc -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/registry-integration/logs -XX:ErrorFile=/data/registry-integration/logs/registry-integration-hs_err_pid%p.log -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -Dnetwork_interface_binding=eth0 : No such file or directory
registry-integration(pid is 7401) is starting, you can check the /data/registry-integration/logs/registry-integration-std.out for more details

**Comment by straybirdzls** [comment]
@xingguangdage 检查下是不是多了空行，看启动参数不对，后面的 jar 都没有

**Comment by xingguangdage** [comment]
是的，跟你写得一样了，eth0后面多了空格，改完还是报错

**Comment by xingguangdage** [comment]
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-27 19:35:53,083][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.

**Comment by atellwu** [comment]
你有钉钉吗？ 我加一下你吧，那样沟通及时一点

**Comment by xingguangdage** [comment]
钉钉号：xingguangdage
