### ISSUE TITLE
软件启动报错

### ISSUE THREAD

**Issue by xingguangdage** [sofastack/sofa-registry#127]
在中标麒麟操作系统上启动软件报错如下
[2020-07-10 08:58:24,432][INFO][main][MetaServerBootstrap] - Open session node register server port 9610 success!
[2020-07-10 08:58:24,434][INFO][main][MetaServerBootstrap] - Open data node register server port 9611 success!
[2020-07-10 08:58:24,436][INFO][main][MetaServerBootstrap] - Open meta server port 9612 success!
[2020-07-10 08:58:25,345][INFO][main][MetaServerBootstrap] - Open http server port 9615 success!
[2020-07-10 08:58:25,539][ERROR][main][MetaServerBootstrap] - Bootstrap Meta Server got error!
java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6296464064937817645.so: /tmp/librocksdbjni6296464064937817645.so: cannot open shared object file: No such file or dir
ectory (Possible cause: architecture word width mismatch)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.alipay.sofa.registry.jraft.bootstrap.RaftServer.<clinit>(RaftServer.java:67)
        at com.alipay.sofa.registry.server.meta.remoting.RaftExchanger.startRaftServer(RaftExchanger.java:94)
        at com.alipay.sofa.registry.server.meta.bootstrap.MetaServerBootstrap.initRaft(MetaServerBootstrap.java:232)
        at com.alipay.sofa.registry.server.meta.bootstrap.MetaServerBootstrap.start(MetaServerBootstrap.java:116)
        at com.alipay.sofa.registry.server.meta.bootstrap.MetaServerInitializerConfiguration.start(MetaServerInitializerConfiguration.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:350)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

### Environment

- SOFARegistry version:
5.4.2
- JVM version (e.g. `java -version`):
# java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
- OS version (e.g. `uname -a`):
# uname -a
Linux 8c-0003.novalocal 4.14.0-115.5.1.el7a.06.aarch64 #1 SMP Tue Jun 18 10:34:55 CST 2019 aarch64 aarch64 aarch64 GNU/Linux
- Maven version:
# mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T03:00:29+08:00)
Maven home: /usr/local/maven
Java version: 1.8.0_251, vendor: Oracle Corporation, runtime: /data/jdk1.8.0_251/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.14.0-115.5.1.el7a.06.aarch64", arch: "aarch64", family: "unix"
- IDE version:

**Comment by dzdx** [comment]
@xingguangdage   看报错 （ architecture word width mismatch ） 像是jre的位宽和加载的rocksdbjni的so不一致
https://github.com/dzdx/rocksdbjni-test  你clone一下这个项目，在启动失败的机器上make一下试试，我看看输出

**Comment by xingguangdage** [comment]
# make
mvn -q clean compile
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.24.215] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
make: *** [run] Error 1

**Comment by dzdx** [comment]
```
#  java -cp rockdb-test-1.0-SNAPSHOT-shaded.jar RocksDBTest
shardLibraryName=rocksdbjni
jniLibraryName=rocksdbjni-linux64
jniLibraryFileName=librocksdbjni-linux64.so
OS=linux
ARCH=aarch64
file: /tmp/librocksdbjni1462377008384919199.so, existed: true
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni1462377008384919199.so: /tmp/librocksdbjni1462377008384919199.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at RocksDBTest.main(RocksDBTest.java:48)
```

5.18.3版本的rocksdbjni不支持aarch64架构，需要jraft依赖的rocksdbjni升级到5.18.4  https://github.com/facebook/rocksdb/pull/6497
