### ISSUE TITLE
启动DataApplication报错

### ISSUE THREAD

**Issue by Scan-jha** [sofastack/sofa-registry#150]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by jha042120** [comment]
报错日志：
"C:\Program Files\Java\jdk1.8.0_31\bin\java.exe" -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=64282 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-javaagent:D:\idea\IntelliJ IDEA 2018.3.3\lib\idea_rt.jar=64283:D:\idea\IntelliJ IDEA 2018.3.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_31\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_31\jre\lib\rt.jar;E:\sofawork\sofa-registry\server\server\data\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\boot\spring-boot-starter\1.5.17.RELEASE\spring-boot-starter-1.5.17.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\boot\spring-boot\1.5.17.RELEASE\spring-boot-1.5.17.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\spring-context\4.3.20.RELEASE\spring-context-4.3.20.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\spring-aop\4.3.20.RELEASE\spring-aop-4.3.20.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\spring-beans\4.3.20.RELEASE\spring-beans-4.3.20.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\spring-expression\4.3.20.RELEASE\spring-expression-4.3.20.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\boot\spring-boot-autoconfigure\1.5.17.RELEASE\spring-boot-autoconfigure-1.5.17.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\boot\spring-boot-starter-logging\1.5.17.RELEASE\spring-boot-starter-logging-1.5.17.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\ch\qos\logback\logback-classic\1.1.11\logback-classic-1.1.11.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\ch\qos\logback\logback-core\1.1.11\logback-core-1.1.11.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\slf4j\jcl-over-slf4j\1.7.25\jcl-over-slf4j-1.7.25.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\slf4j\jul-to-slf4j\1.7.9\jul-to-slf4j-1.7.9.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\slf4j\log4j-over-slf4j\1.7.25\log4j-over-slf4j-1.7.25.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\springframework\spring-core\4.3.20.RELEASE\spring-core-4.3.20.RELEASE.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;E:\sofawork\sofa-registry\server\common\model\target\classes;E:\sofawork\sofa-registry\core\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\fasterxml\jackson\core\jackson-annotations\2.8.0\jackson-annotations-2.8.0.jar;E:\sofawork\sofa-registry\server\common\util\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\io\dropwizard\metrics\metrics-core\4.0.2\metrics-core-4.0.2.jar;E:\sofawork\sofa-registry\server\consistency\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\alipay\sofa\bolt\1.6.2\bolt-1.6.2.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\io\netty\netty-all\4.1.42.Final\netty-all-4.1.42.Final.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\slf4j\slf4j-api\1.7.21\slf4j-api-1.7.21.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\alipay\sofa\common\sofa-common-tools\1.0.12\sofa-common-tools-1.0.12.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\alipay\sofa\hessian\3.3.8\hessian-3.3.8.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\google\guava\guava\18.0\guava-18.0.jar;E:\sofawork\sofa-registry\server\store\jraft\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\alipay\sofa\jraft-core\1.3.5.Alpha1\jraft-core-1.3.5.Alpha1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\ow2\asm\asm\6.0\asm-6.0.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\rocksdb\rocksdbjni\6.4.6\rocksdbjni-6.4.6.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\net\java\dev\jna\jna\4.2.2\jna-4.2.2.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\jctools\jctools-core\2.1.1\jctools-core-2.1.1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\lmax\disruptor\3.3.7\disruptor-3.3.7.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\google\protobuf\protobuf-java\3.5.1\protobuf-java-3.5.1.jar;E:\sofawork\sofa-registry\server\remoting\bolt\target\classes;E:\sofawork\sofa-registry\server\remoting\api\target\classes;E:\sofawork\sofa-registry\server\store\api\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\commons-io\commons-io\2.4\commons-io-2.4.jar;E:\sofawork\sofa-registry\server\remoting\http\target\classes;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\core\jersey-server\2.26\jersey-server-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\core\jersey-common\2.26\jersey-common-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\hk2\osgi-resource-locator\1.0.1\osgi-resource-locator-1.0.1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\core\jersey-client\2.26\jersey-client-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\javax\ws\rs\javax.ws.rs-api\2.1\javax.ws.rs-api-2.1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\media\jersey-media-jaxb\2.25.1\jersey-media-jaxb-2.25.1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\hk2\hk2-api\2.5.0-b32\hk2-api-2.5.0-b32.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\hk2\external\javax.inject\2.5.0-b42\javax.inject-2.5.0-b42.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\containers\jersey-container-netty-http\2.26\jersey-container-netty-http-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\connectors\jersey-netty-connector\2.26\jersey-netty-connector-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\containers\jersey-container-jdk-http\2.26\jersey-container-jdk-http-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\containers\jersey-container-jetty-http\2.26\jersey-container-jetty-http-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\inject\jersey-hk2\2.26\jersey-hk2-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\hk2\hk2-locator\2.5.0-b42\hk2-locator-2.5.0-b42.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\hk2\external\aopalliance-repackaged\2.5.0-b42\aopalliance-repackaged-2.5.0-b42.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\hk2\hk2-utils\2.5.0-b42\hk2-utils-2.5.0-b42.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\javax\inject\javax.inject\1\javax.inject-1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\javassist\javassist\3.21.0-GA\javassist-3.21.0-GA.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\media\jersey-media-json-jackson\2.26\jersey-media-json-jackson-2.26.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\glassfish\jersey\ext\jersey-entity-filtering\2.25.1\jersey-entity-filtering-2.25.1.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\fasterxml\jackson\core\jackson-databind\2.8.11.2\jackson-databind-2.8.11.2.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\fasterxml\jackson\core\jackson-core\2.8.11\jackson-core-2.8.11.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.8.11\jackson-module-jaxb-annotations-2.8.11.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\eclipse\jetty\jetty-server\9.4.19.v20190610\jetty-server-9.4.19.v20190610.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\eclipse\jetty\jetty-http\9.4.19.v20190610\jetty-http-9.4.19.v20190610.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\eclipse\jetty\jetty-io\9.4.19.v20190610\jetty-io-9.4.19.v20190610.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\eclipse\jetty\jetty-util\9.4.19.v20190610\jetty-util-9.4.19.v20190610.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\eclipse\jetty\jetty-continuation\9.4.19.v20190610\jetty-continuation-9.4.19.v20190610.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\hibernate\hibernate-validator\5.3.6.Final\hibernate-validator-5.3.6.Final.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\com\fasterxml\classmate\1.3.4\classmate-1.3.4.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven\apache-maven-3.6.1\MavenRepository\mavensofa_jar\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar" com.alipay.sofa.registry.server.data.DataApplication
[2020-11-26 11:56:15,488][INFO][main][SpringApplication] - 
  ____        _          ____
 |  _ \  __ _| |_ __ _  / ___|  ___ _ ____   _____ _ __ 
 | | | |/ _` | __/ _` | \___ \ / _ \ '__\ \ / / _ \ '__|
 | |_| | (_| | || (_| |  ___) |  __/ |   \ V /  __/ |   
 |____/ \__,_|\__\__,_| |____/ \___|_|    \_/ \___|_|   
                                                        

[2020-11-26 11:56:15,541][INFO][main][DataApplication] - Starting DataApplication on DESKTOP-G85466D with PID 69924 (E:\sofawork\sofa-registry\server\server\data\target\classes started by jha04 in E:\sofawork\sofa-registry)
[2020-11-26 11:56:15,542][INFO][main][DataApplication] - No active profile set, falling back to default profiles: default
[2020-11-26 11:56:16,228][INFO][main][DATA-START-LOGS] - [DataChangeEventQueue_0] start DataChangeEventQueue success
[2020-11-26 11:56:16,228][INFO][main][DATA-START-LOGS] - [DataChangeEventQueue_1] start DataChangeEventQueue success
[2020-11-26 11:56:16,229][INFO][main][DATA-START-LOGS] - [DataChangeEventQueue_2] start DataChangeEventQueue success
[2020-11-26 11:56:16,229][INFO][main][DATA-START-LOGS] - [DataChangeEventQueue_3] start DataChangeEventQueue success
[2020-11-26 11:56:16,231][INFO][main][DATA-START-LOGS] - start DisconnectEventHandler success
[2020-11-26 11:56:16,367][INFO][main][DATA-START-LOGS] - [LocalDataServerCleanHandler] start LocalDataServerCleanHandler success
[2020-11-26 11:56:16,424][INFO][main][DATA-START-LOGS] - [DataChangeHandler] notify datum in queue:DataChangeEventQueue_0 success
[2020-11-26 11:56:16,424][INFO][main][DATA-START-LOGS] - [DataChangeHandler] notify datum in queue:DataChangeEventQueue_1 success
[2020-11-26 11:56:16,424][INFO][main][DATA-START-LOGS] - [DataChangeHandler] notify datum in queue:DataChangeEventQueue_2 success
[2020-11-26 11:56:16,424][INFO][main][DATA-START-LOGS] - [DataChangeHandler] notify datum in queue:DataChangeEventQueue_3 success
[2020-11-26 11:56:16,640][INFO][main][DataServerBootstrap] - begin start server
[2020-11-26 11:56:16,645][INFO][main][DataServerBootstrap] - the configuration items are as follows: com.alipay.sofa.registry.server.data.bootstrap.DataServerConfig@579d011c[
  port=9620
  syncDataPort=9621
  metaServerPort=9611
  httpServerPort=9622
  queueCount=4
  queueSize=10240
  notifyIntervalMs=500
  clientOffDelayMs=1000
  notifyTempDataIntervalMs=10
  rpcTimeout=3000
  commonConfig=com.alipay.sofa.registry.server.data.bootstrap.CommonConfig@3670f00
  metaIps=<null>
  storeNodes=3
  numberOfReplicas=1000
  localDataServerCleanDelay=1800000
  getDataExecutorMinPoolSize=80
  getDataExecutorMaxPoolSize=400
  getDataExecutorQueueSize=10000
  getDataExecutorKeepAliveTime=60
  notifyDataSyncExecutorMinPoolSize=80
  notifyDataSyncExecutorMaxPoolSize=400
  notifyDataSyncExecutorQueueSize=700
  notifyDataSyncExecutorKeepAliveTime=60
  notifySessionRetryFirstDelay=3000
  notifySessionRetryIncrementDelay=3000
  notifySessionRetryTimes=5
  publishExecutorMinPoolSize=200
  publishExecutorMaxPoolSize=400
  publishExecutorQueueSize=10000
  renewDatumExecutorMinPoolSize=100
  renewDatumExecutorMaxPoolSize=400
  renewDatumExecutorQueueSize=100000
  datumTimeToLiveSec=900
  datumLeaseManagerExecutorThreadSize=1
  datumLeaseManagerExecutorQueueSize=1000000
  sessionServerNotifierRetryExecutorThreadSize=10
  sessionServerNotifierRetryExecutorQueueSize=10000
  renewEnableDelaySec=30
  dataSyncDelayTimeout=1000
  dataSyncNotifyRetry=3
  sessionDisconnectDelayMs=30000
]
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Logback ]
[2020-11-26 11:56:16,842][ERROR][main][DataServerBootstrap] - Data server start error! port:9620
java.lang.RuntimeException: Start bolt server error!
	at com.alipay.sofa.registry.remoting.bolt.BoltServer.startServer(BoltServer.java:98)
	at com.alipay.sofa.registry.remoting.bolt.exchange.BoltExchange.open(BoltExchange.java:65)
	at com.alipay.sofa.registry.remoting.bolt.exchange.BoltExchange.open(BoltExchange.java:36)
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap.openDataServer(DataServerBootstrap.java:148)
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap.start(DataServerBootstrap.java:125)
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerInitializer.start(DataServerInitializer.java:47)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:350)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.alipay.sofa.registry.server.data.DataApplication.main(DataApplication.java:41)
Caused by: java.lang.IllegalStateException: ERROR: Failed to start the Server!
	at com.alipay.remoting.AbstractRemotingServer.startup(AbstractRemotingServer.java:108)
	at com.alipay.remoting.AbstractRemotingServer.start(AbstractRemotingServer.java:81)
	at com.alipay.sofa.registry.remoting.bolt.BoltServer.startServer(BoltServer.java:93)
	... 18 common frames omitted
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.Net.bind(Net.java:428)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)
[2020-11-26 11:56:16,850][ERROR][main][SpringApplication] - Application startup failed
org.springframework.context.ApplicationContextException: Failed to start bean 'com.alipay.sofa.registry.server.data.bootstrap.DataServerInitializer'; nested exception is java.lang.RuntimeException: start server error
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:350)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.alipay.sofa.registry.server.data.DataApplication.main(DataApplication.java:41)
Caused by: java.lang.RuntimeException: start server error
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap.start(DataServerBootstrap.java:141)
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerInitializer.start(DataServerInitializer.java:47)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	... 12 common frames omitted
Caused by: java.lang.RuntimeException: Data server start error!
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap.openDataServer(DataServerBootstrap.java:156)
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap.start(DataServerBootstrap.java:125)
	... 14 common frames omitted
Caused by: java.lang.RuntimeException: Start bolt server error!
	at com.alipay.sofa.registry.remoting.bolt.BoltServer.startServer(BoltServer.java:98)
	at com.alipay.sofa.registry.remoting.bolt.exchange.BoltExchange.open(BoltExchange.java:65)
	at com.alipay.sofa.registry.remoting.bolt.exchange.BoltExchange.open(BoltExchange.java:36)
	at com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap.openDataServer(DataServerBootstrap.java:148)
	... 15 common frames omitted
Caused by: java.lang.IllegalStateException: ERROR: Failed to start the Server!
	at com.alipay.remoting.AbstractRemotingServer.startup(AbstractRemotingServer.java:108)
	at com.alipay.remoting.AbstractRemotingServer.start(AbstractRemotingServer.java:81)
	at com.alipay.sofa.registry.remoting.bolt.BoltServer.startServer(BoltServer.java:93)
	... 18 common frames omitted
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.Net.bind(Net.java:428)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jha042120** [comment]
上面那个是启动工程控制台报的错。然后我在linux上搭建了一个注册中心，这个是日志文件：
帮忙看一下。谢谢

**Comment by jha042120** [comment]
[common-default.log](https://github.com/sofastack/sofa-registry/files/5600669/common-default.log)

**Comment by jha042120** [comment]
这个是注册中心logs下bolt下的文件日志，我看到这个在报错

**Comment by dzdx** [comment]
`Caused by: java.net.BindException: Address already in use: bind` 

Data启动需要listen 3个端口，检查一下端口有没有被占用
- 9620
- 9621
- 9622
