### ISSUE TITLE
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by FoamValue** [sofastack/sofa-registry#96]
### Describe the bug

按照[官网步骤](https://www.sofastack.tech/projects/sofa-registry/server-quick-start/)，本地运行的时候，出现了错误日志。

`[2020-03-07 20:25:25,644][INFO][main][MetaServerBootstrap] - Open session node register server port 9610 success!
[2020-03-07 20:25:25,648][INFO][main][MetaServerBootstrap] - Open data node register server port 9611 success!
[2020-03-07 20:25:25,650][INFO][main][MetaServerBootstrap] - Open meta server port 9612 success!
[2020-03-07 20:25:26,590][INFO][main][MetaServerBootstrap] - Open http server port 9615 success!
[2020-03-07 20:25:27,401][INFO][main][MetaServerBootstrap] - Raft server port 9614 start success!group RegistryGroup
[2020-03-07 20:25:27,401][INFO][main][MetaServerBootstrap] - Raft client connect success!
[2020-03-07 20:25:27,405][INFO][main][MetaServerBootstrap] - Raft start CliService success!
[2020-03-07 20:25:27,406][INFO][main][MetaServerInitializerConfiguration] - Started MetaServer
[2020-03-07 20:25:28,165][INFO][main][RegistryApplication] - localhost:9615 health check success.
[2020-03-07 20:25:29,253][INFO][main][DataServerBootstrap] - begin start server
[2020-03-07 20:25:29,254][INFO][main][DataServerBootstrap] - the configuration items are as follows: com.alipay.sofa.registry.server.data.bootstrap.DataServerConfig@7d42c224[
  port=9620
  syncDataPort=9621
  metaServerPort=9611
  httpServerPort=9622
  queueCount=4
  queueSize=10240
  notifyIntervalMs=500
  clientOffDelayMs=0
  notifyTempDataIntervalMs=0
  rpcTimeout=3000
  commonConfig=com.alipay.sofa.registry.server.data.bootstrap.CommonConfig@56aaaecd
  metaIps=<null>
  storeNodes=3
  numberOfReplicas=1000
  localDataServerCleanDelay=1800000
  getDataExecutorMinPoolSize=80
  getDataExecutorMaxPoolSize=400
  getDataExecutorQueueSize=10000
  getDataExecutorKeepAliveTime=60
  notifyDataSyncExecutorMinPoolSize=80
  notifyDataSyncExecutorMaxPoolSize=400
  notifyDataSyncExecutorQueueSize=700
  notifyDataSyncExecutorKeepAliveTime=60
  notifySessionRetryFirstDelay=3000
  notifySessionRetryIncrementDelay=3000
  notifySessionRetryTimes=5
  publishExecutorMinPoolSize=200
  publishExecutorMaxPoolSize=400
  publishExecutorQueueSize=10000
  renewDatumExecutorMinPoolSize=100
  renewDatumExecutorMaxPoolSize=400
  renewDatumExecutorQueueSize=100000
  datumTimeToLiveSec=20
  datumLeaseManagerExecutorThreadSize=1
  datumLeaseManagerExecutorQueueSize=1000000
  sessionServerNotifierRetryExecutorThreadSize=10
  sessionServerNotifierRetryExecutorQueueSize=10000
  renewEnableDelaySec=30
  dataSyncDelayTimeout=1000
  dataSyncNotifyRetry=3
]
[2020-03-07 20:25:29,260][INFO][main][DataServerBootstrap] - Data server for session started! port:9620
[2020-03-07 20:25:29,269][INFO][main][DataServerBootstrap] - Data server for sync started! port:9621
[2020-03-07 20:25:29,388][INFO][main][DataServerBootstrap] - Open http server port 9622 success!

[2020-03-07 20:25:29,468][INFO][main][DataServerBootstrap] - raft client started!Leader is 192.168.50.10:9614
[2020-03-07 20:25:29,474][INFO][main][DataServerBootstrap] - Fetch enableDataDatumExpire but no data existed, current config not change!
[2020-03-07 20:25:29,480][INFO][main][DataServerBootstrap] - start server success
[2020-03-07 20:25:29,501][ERROR][main][RegistryApplication] - localhost:9622 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
	at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
	at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
	at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-03-07 20:25:29,502][ERROR][main][RegistryApplication] - localhost:9622 health check failed.
[2020-03-07 20:25:30,510][ERROR][main][RegistryApplication] - localhost:9622 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
	at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
	at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
	at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-03-07 20:25:30,510][ERROR][main][RegistryApplication] - localhost:9622 health check failed.
[2020-03-07 20:25:31,514][INFO][main][RegistryApplication] - localhost:9622 health check success.
[2020-03-07 20:25:32,788][INFO][main][SessionServerBootstrap] - the configuration items are as follows: com.alipay.sofa.registry.server.session.bootstrap.SessionServerConfigBean@62315f22[
  serverPort=9600
  metaServerPort=9610
  dataServerPort=9620
  httpServerPort=9603
  schedulerHeartbeatTimeout=30
  schedulerHeartbeatFirstDelay=30
  schedulerHeartbeatExpBackOffBound=10
  schedulerGetSessionNodeTimeout=3
  schedulerGetSessionNodeFirstDelay=5
  schedulerGetSessionNodeExpBackOffBound=10
  schedulerFetchDataTimeout=3
  schedulerFetchDataFirstDelay=3
  schedulerFetchDataExpBackOffBound=10
  schedulerConnectMetaTimeout=5
  schedulerConnectMetaFirstDelay=5
  schedulerConnectMetaExpBackOffBound=3
  schedulerConnectDataTimeout=10
  schedulerConnectDataFirstDelay=10
  schedulerConnectDataExpBackOffBound=3
  schedulerCleanInvalidClientTimeOut=3
  schedulerCleanInvalidClientFirstDelay=10
  schedulerCleanInvalidClientBackOffBound=5
  cancelDataTaskRetryTimes=2
  cancelDataTaskRetryFirstDelay=500
  cancelDataTaskRetryIncrementDelay=500
  publishDataTaskRetryTimes=2
  publishDataTaskRetryFirstDelay=3000
  publishDataTaskRetryIncrementDelay=5000
  unPublishDataTaskRetryTimes=2
  unPublishDataTaskRetryFirstDelay=3000
  unPublishDataTaskRetryIncrementDelay=5000
  datumSnapshotTaskRetryTimes=1
  datumSnapshotTaskRetryFirstDelay=5000
  datumSnapshotTaskRetryIncrementDelay=5000
  renewDatumTaskRetryTimes=1
  dataChangeFetchTaskRetryTimes=3
  subscriberRegisterFetchRetryTimes=3
  receivedDataMultiPushTaskRetryTimes=3
  sessionRegisterDataServerTaskRetryTimes=5
  defaultSessionExecutorMinPoolSize=4
  defaultSessionExecutorMaxPoolSize=20
  defaultSessionExecutorKeepAliveTime=60
  accessDataExecutorMinPoolSize=100
  accessDataExecutorMaxPoolSize=400
  accessDataExecutorQueueSize=10000
  accessDataExecutorKeepAliveTime=60
  pushTaskExecutorMinPoolSize=40
  pushTaskExecutorMaxPoolSize=400
  pushTaskExecutorQueueSize=100000
  pushTaskExecutorKeepAliveTime=60
  dataChangeExecutorMinPoolSize=40
  dataChangeExecutorMaxPoolSize=400
  dataChangeExecutorQueueSize=100000
  dataChangeExecutorKeepAliveTime=60
  connectClientExecutorMinPoolSize=60
  connectClientExecutorMaxPoolSize=400
  connectClientExecutorQueueSize=10000
  dataChangeFetchTaskMaxBufferSize=1000000
  dataChangeFetchTaskWorkerSize=100
  clientNodeExchangeTimeOut=1000
  dataNodeExchangeTimeOut=3000
  dataNodeExchangeForFetchDatumTimeOut=5000
  metaNodeExchangeTimeOut=3000
  numberOfReplicas=1000
  userDataPushRetryWheelTicksSize=5120
  userDataPushRetryWheelTicksDuration=100
  userDataPushRetryExecutorQueueSize=1000000
  userDataPushRetryExecutorThreadSize=10
  renewDatumWheelTicksSize=2048
  renewDatumWheelTicksDuration=500
  renewDatumWheelTaskDelaySec=180
  renewDatumWheelTaskRandomFirstDelaySec=200
  renewDatumWheelThreadSize=10
  renewDatumWheelQueueSize=10000
  pushDataTaskRetryFirstDelay=500
  pushDataTaskRetryIncrementDelay=500
  pushTaskConfirmWaitTimeout=10000
  pushTaskConfirmCheckWheelTicksSize=1024
  pushTaskConfirmCheckWheelTicksDuration=100
  pushTaskConfirmCheckExecutorQueueSize=10000
  pushTaskConfirmCheckExecutorThreadSize=10
  publishDataExecutorMinPoolSize=100
  publishDataExecutorMaxPoolSize=400
  publishDataExecutorQueueSize=10000
  publishDataExecutorKeepAliveTime=60
  accessLimitRate=100000.0
  sessionServerRegion=DEFAULT_ZONE
  sessionServerDataCenter=DefaultDataCenter
  stopPushSwitch=false
  beginDataFetchTask=false
  invalidForeverZones=
  invalidIgnoreDataidRegex=
  invalidForeverZonesSet=<null>
  invalidIgnoreDataIdPattern=<null>
  blacklistPubDataIdRegex=
  blacklistSubDataIdRegex=
  renewAndSnapshotSilentPeriodSec=20
  writeDataAcceptorQueueSize=10000
  dataNodeRetryExecutorQueueSize=1000000
  dataNodeRetryExecutorThreadSize=100
  dataClientConnNum=10
  sessionSchedulerPoolSize=6
  commonConfig=com.alipay.sofa.registry.server.session.bootstrap.CommonConfig@4b6579e8[
  localDataCenter=DefaultDataCenter
  localRegion=DEFAULT_ZONE
  metaNode={DefaultDataCenter=[localhost]}
]
]
[2020-03-07 20:25:32,794][INFO][main][SessionServerBootstrap] - Session server Environment: DataCenter DefaultDataCenter,Region DEFAULT_ZONE,ProcessId c0a8320a1583583932794100118452
[2020-03-07 20:25:32,799][INFO][main][SessionServerBootstrap] - Raft Client started! Leader:192.168.50.10:9614
[2020-03-07 20:25:32,854][INFO][main][SessionServerBootstrap] - Register MetaServer Session Node success!get data node list {DefaultDataCenter={192.168.50.10=DataNode{ip=192.168.50.10}}}
[2020-03-07 20:25:32,860][INFO][main][SessionServerBootstrap] - Get all dataCenter from meta Server success!
[2020-03-07 20:25:32,868][INFO][main][SessionServerBootstrap] - MetaServer connected meta server! Port:9610
[2020-03-07 20:25:32,872][INFO][main][SessionServerBootstrap] - Session Scheduler started!
[2020-03-07 20:25:33,043][INFO][main][SessionServerBootstrap] - Open http server port 9603 success!
[2020-03-07 20:25:33,048][INFO][main][SessionServerBootstrap] - Session server started! port:9600
[2020-03-07 20:25:33,150][INFO][main][SessionServerBootstrap] - Initialized Session Server...
[2020-03-07 20:25:33,151][INFO][main][SessionServerInitializer] - Started SessionServer
[2020-03-07 20:25:33,205][INFO][main][RegistryApplication] - localhost:9603 health check success.`

### Environment

- SOFARegistry version:  master 分支
- JVM version (e.g. `java -version`):  java version "1.8.0_211"
- OS version (e.g. `uname -a`): Darwin FoamValue-MBP.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
- Maven version: 3.6.3

**Comment by straybirdzls** [comment]
这个报错没有影响。启动 data 之后，刚开始健康检查没有通过，因为此时 data 的状态是 INITIAL 状态 ，故而此时健康检查会返回 500(参考 `com.alipay.sofa.registry.server.data.resource.HealthResource#checkHealth`) ，在 `com.alipay.sofa.registry.server.integration.RegistryApplication` 的 `com.alipay.sofa.registry.server.integration.RegistryApplication#waitClusterStart`  中会轮询等待健康检查的状态，直至成功，从你上上面的日志来看，前两次失败了，第三次成功了，此时 data 的状态才是 WORKING 状态(参考 `com.alipay.sofa.registry.server.data.util.LocalServerStatusEnum` 中的定义)。

不过这个报错信息的确会让人有些误会，可以优化下，不知你是否有兴趣 PR 优化下？

**Comment by FoamValue** [comment]
:) 只想到了一个粗暴的思路，设置阀值对外抛ERROR。
